### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by pravocodes**
Entry point for project

### CODE REVIEW

**Comment by akkupy** [comment]
Will You add more files in this folder?

**Comment by pravocodes** [comment]
yup sure

**Comment by akkupy** [comment]
Create a PR after you have added all the files

**Comment by pravocodes** [comment]
you have not allowed to upload the set of files how can I make single pull request with multiple file in one folder. can you please brief me I am new learning right now.

**Comment by akkupy** [comment]
Fork and clone this repo into your local machine. add the files in the folder and then commit and push the changes into your repo

Then Create a PR to me.

Refer Youtube for a Video Tutorial if you are new to git and github

**Pull request closed without merging**
