### PR TITLE
Added Basic C++ CODES

### PR DESCRIPTION
**Pull request by aaryansood2512chitkara**
Hello Sir,
I have added basic c++ codes to your repository
Hope! You merge it .

### CODE REVIEW

**Comment by akkupy** [comment]
Heyy..it would be great if you add those programs inside cpp folder..:)

**Comment by aaryansood2512chitkara** [comment]
sure

**Comment by akkupy** [comment]
Delete the cpp Programs added on root directory and add those programs in cpp folder and I'll merge the PR.

**Comment by aaryansood2512chitkara** [comment]
Ok, will do that.

**Comment by aaryansood2512chitkara** [comment]
I have deleted the programs from root directory.
Please merge

**Comment by aaryansood2512chitkara** [comment]
I have deleted. Kindly Check

**Comment by akkupy** [comment]
Heyy..You have "accidentally" deleted the CONTRIBUTING.md file of the repository which was an important file.
Please re sync your repository with mine and add your prgms inside cpp folder.
I'm unable to merge the PR because of the missing CONTRIBUTING.md file.
Kindly recheck and sync with my repo

**Comment by aaryansood2512chitkara** [comment]
I have done
Kindly see😊

**Comment by aaryansood2512chitkara** [comment]
Hello Sir,
I have added basic c++ codes to your repository
Hope! You merge it .

**Pull request merged**
